import Navbar from "./components/Navbar";
import "./globals.css";
import { Open_Sans, Montserrat, Inter } from "next/font/google";
import Footer from "./components/Footer";

export const open = Open_Sans({
  subsets: ["latin"],
  variable: ["--font-headline"],
});
export const montserrat = Montserrat({
  subsets: ["latin"],
  variable: ["--font-linkline"],
});
export const inter = Inter({
  subsets: ["latin"],
  variable: ["--font-regular"],
});

export const metadata = {
  title: "GOL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${open.variable} ${montserrat.variable} ${inter.variable}`}
    >
      <body className="commonHero w-full">
        <Navbar />
        <div className="section">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
